import { BaseDto } from 'ws-request-hook';
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.2.0.0 (NJsonSchema v11.1.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming




export interface ServerSendsQuestionDto extends BaseDto {
    questionId?: string;
    questionText?: string;
    options?: QuestionOptionDto[];
}

export interface QuestionOptionDto {
    optionId?: string;
    optionText?: string;
}

export interface ClientAnswersQuestionDto extends BaseDto {
    gameId?: string;
    questionId?: string;
    selectedOptionId?: string;
}

export interface MemberHasLeftDto extends BaseDto {
    memberId?: string;
}

export interface ServerPutsClientInLobbyAndBroadcastsToEveryoneDto extends BaseDto {
    allPlayers?: PlayerInfoDto[];
}

export interface PlayerInfoDto {
    id?: string;
    nickname?: string;
}

export interface AdminRequestsEndQuestionDto extends BaseDto {
    gameId?: string;
    questionId?: string;
}

export interface AdminRequestsNextQuestionDto extends BaseDto {
    gameId?: string;
}

export interface AdminStartsGameDto extends BaseDto {
    gameId?: string;
}

export interface ClientEntersLobbyDto extends BaseDto {
    nickname?: string;
}

export interface ServerConfirmsDto extends BaseDto {
    success?: boolean;
}

export interface ServerSendsErrorMessageDto extends BaseDto {
    error?: string;
}

export interface ServerShowsResultsDto extends BaseDto {
    eventType?: string;
    results?: PlayerAnswerResult[];
}

export interface PlayerAnswerResult {
    playerId?: string;
    selectedOptionId?: string | undefined;
    isCorrect?: boolean;
}

export interface ServerTellsPlayersGameStartedDto extends BaseDto {
    gameId?: string;
    eventType?: string;
}

/** Available eventType constants */
export enum StringConstants {
    ServerSendsQuestionDto = "ServerSendsQuestionDto",
    ClientAnswersQuestionDto = "ClientAnswersQuestionDto",
    MemberHasLeftDto = "MemberHasLeftDto",
    ServerPutsClientInLobbyAndBroadcastsToEveryoneDto = "ServerPutsClientInLobbyAndBroadcastsToEveryoneDto",
    AdminRequestsEndQuestionDto = "AdminRequestsEndQuestionDto",
    AdminRequestsNextQuestionDto = "AdminRequestsNextQuestionDto",
    AdminStartsGameDto = "AdminStartsGameDto",
    ClientEntersLobbyDto = "ClientEntersLobbyDto",
    ServerConfirmsDto = "ServerConfirmsDto",
    ServerSendsErrorMessageDto = "ServerSendsErrorMessageDto",
    ServerShowsResultsDto = "ServerShowsResultsDto",
    ServerTellsPlayersGameStartedDto = "ServerTellsPlayersGameStartedDto",
}

